name: Rust
env:
  CARGO_TERM_COLOR: always
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manoadamro/rust-release@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}

