name: Rust

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
      - name: Build
        with:
          command: build
          args: --verbose
      - name: Run Tests
        with:
          command: test
          args: --verbose
      
